package com.tivit.snap_api.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Getter
@Setter
@Component
@ConfigurationProperties(prefix = "snap.api")
public class SnapApiProperties {
    private String basePath = "/api";
    private String title = "SnapREST API";
    private String description = "API automatically generated by SnapREST";
    private String version = "1.0";
}